"""initial schema spec section 9

Revision ID: a14e1729bcaf
Revises: 
Create Date: 2026-05-25 22:04:32.108474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a14e1729bcaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('city_key', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('city_key')
    )
    op.create_table('crisis_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('article_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('high_crisis_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mapped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unmapped_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crisis_snapshots_captured_at'), 'crisis_snapshots', ['captured_at'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_captured_at'), 'insights', ['captured_at'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_captured_at'), 'keywords', ['captured_at'], unique=False)
    op.create_table('leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('photo_uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_ticker',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=True),
    sa.Column('delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_ticker_captured_at'), 'market_ticker', ['captured_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('answer_label', sa.String(length=120), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('timeframe', sa.String(length=80), nullable=True),
    sa.Column('tone', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_captured_at'), 'predictions', ['captured_at'], unique=False)
    op.create_table('social_actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('followers', sa.BigInteger(), nullable=True),
    sa.Column('influence', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('credibility', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('sentiment', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('posts_7d', sa.Integer(), nullable=True),
    sa.Column('brand_mentions', sa.Integer(), nullable=True),
    sa.Column('avg_engagement', sa.Integer(), nullable=True),
    sa.Column('total_engagement', sa.BigInteger(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_summary', sa.Text(), nullable=True),
    sa.Column('influence_analysis', sa.Text(), nullable=True),
    sa.Column('collab_opportunity', sa.Text(), nullable=True),
    sa.Column('recommended_actions', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_actors_handle'), 'social_actors', ['handle'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('cadence_sec', sa.Integer(), server_default='1800', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('actor_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_uri', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['social_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actor_posts_actor_id'), 'actor_posts', ['actor_id'], unique=False)
    op.create_index(op.f('ix_actor_posts_posted_at'), 'actor_posts', ['posted_at'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_uri', sa.Text(), nullable=True),
    sa.Column('fts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(body, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=False)
    op.create_index('ix_articles_fts', 'articles', ['fts'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_articles_source_id'), 'articles', ['source_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('meta_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('city_key', sa.String(length=120), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('heat', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('severity_sum', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('article_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dominant_issue', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['city_key'], ['cities.city_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_metrics_captured_at'), 'city_metrics', ['captured_at'], unique=False)
    op.create_index(op.f('ix_city_metrics_city_key'), 'city_metrics', ['city_key'], unique=False)
    op.create_table('dashboard_layouts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('layout_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('leader_articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('crisis_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['leaders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leader_articles_leader_id'), 'leader_articles', ['leader_id'], unique=False)
    op.create_table('leader_sentiment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('prediction_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['leaders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leader_sentiment_captured_at'), 'leader_sentiment', ['captured_at'], unique=False)
    op.create_index(op.f('ix_leader_sentiment_leader_id'), 'leader_sentiment', ['leader_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('article_enrichment',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('dominant_issue', sa.String(length=100), nullable=True),
    sa.Column('secondary_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_enrichment')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_leader_sentiment_leader_id'), table_name='leader_sentiment')
    op.drop_index(op.f('ix_leader_sentiment_captured_at'), table_name='leader_sentiment')
    op.drop_table('leader_sentiment')
    op.drop_index(op.f('ix_leader_articles_leader_id'), table_name='leader_articles')
    op.drop_table('leader_articles')
    op.drop_table('dashboard_layouts')
    op.drop_index(op.f('ix_city_metrics_city_key'), table_name='city_metrics')
    op.drop_index(op.f('ix_city_metrics_captured_at'), table_name='city_metrics')
    op.drop_table('city_metrics')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_articles_source_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index('ix_articles_fts', table_name='articles', postgresql_using='gin')
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_actor_posts_posted_at'), table_name='actor_posts')
    op.drop_index(op.f('ix_actor_posts_actor_id'), table_name='actor_posts')
    op.drop_table('actor_posts')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_index(op.f('ix_social_actors_handle'), table_name='social_actors')
    op.drop_table('social_actors')
    op.drop_index(op.f('ix_predictions_captured_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_market_ticker_captured_at'), table_name='market_ticker')
    op.drop_table('market_ticker')
    op.drop_table('leaders')
    op.drop_index(op.f('ix_keywords_captured_at'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_insights_captured_at'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_crisis_snapshots_captured_at'), table_name='crisis_snapshots')
    op.drop_table('crisis_snapshots')
    op.drop_table('cities')
    # ### end Alembic commands ###
