apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: registry.digitalocean.com/nexorus-registry/danantara
  newName: registry.digitalocean.com/nexorus-registry/danantara
  newTag: sha-97bbc0a
patches:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: atlas.nexorus-alpha.io
  target:
    kind: Ingress
    name: danantara
