import { Kysely, PostgresDialect } from "kysely";
import { Pool } from "pg";

import type { DB } from "./types.gen";

/**
 * Read-only Kysely client over the Alembic-owned Postgres schema (spec §4).
 *
 * `types.gen.ts` is generated by `kysely-codegen` against the live schema and is
 * never hand-edited. The BFF reads through this client; the TS side never migrates
 * the database — Alembic (Python) is the single source of schema truth.
 *
 * Lazily constructed so importing this module doesn't open a pool at build time.
 */
let client: Kysely<DB> | null = null;

export function getDb(): Kysely<DB> {
  if (client === null) {
    client = new Kysely<DB>({
      dialect: new PostgresDialect({
        pool: new Pool({ connectionString: process.env.DATABASE_URL }),
      }),
    });
  }
  return client;
}
