/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ActorPosts {
  actor_id: number;
  comments: number | null;
  id: Generated<Int8>;
  likes: number | null;
  posted_at: Timestamp | null;
  raw_uri: string | null;
  text: string | null;
  views: Int8 | null;
}

export interface AiConversations {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  user_id: number | null;
}

export interface AiMessages {
  content: string | null;
  conversation_id: Int8;
  cost: Numeric | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  model: string | null;
  role: string;
  tokens: number | null;
}

export interface AlembicVersion {
  version_num: string;
}

export interface ArticleEnrichment {
  ai_reasoning: string | null;
  article_id: Int8;
  city: string | null;
  cost: Numeric | null;
  dominant_issue: string | null;
  enriched_at: Generated<Timestamp | null>;
  lat: Numeric | null;
  level: string | null;
  lng: Numeric | null;
  model: string | null;
  province: string | null;
  score: Numeric | null;
  secondary_issues: Json | null;
  sentiment: string | null;
  tokens: number | null;
}

export interface Articles {
  body: string | null;
  canonical_url: string | null;
  content_hash: string | null;
  fetched_at: Generated<Timestamp>;
  fts: Generated<string | null>;
  id: Generated<Int8>;
  published_at: Timestamp | null;
  raw_uri: string | null;
  source_id: number | null;
  title: string | null;
  url: string;
}

export interface AuditLog {
  action: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  meta_jsonb: Json | null;
  target: string | null;
  user_id: number | null;
}

export interface Cities {
  city: string | null;
  city_key: string;
  lat: Numeric | null;
  lng: Numeric | null;
  province: string | null;
}

export interface CityMetrics {
  article_count: Generated<number>;
  captured_at: Generated<Timestamp>;
  city_key: string;
  dominant_issue: string | null;
  heat: Numeric | null;
  id: Generated<Int8>;
  severity_sum: Numeric | null;
}

export interface CrisisSnapshots {
  article_count: Generated<number>;
  captured_at: Generated<Timestamp>;
  high_crisis_count: Generated<number>;
  id: Generated<Int8>;
  level: string | null;
  mapped_count: Generated<number>;
  score: Numeric | null;
  unmapped_count: Generated<number>;
}

export interface DashboardLayouts {
  layout_jsonb: Json;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface Insights {
  action: string | null;
  captured_at: Generated<Timestamp>;
  id: Generated<number>;
  text: string | null;
  title: string | null;
}

export interface Keywords {
  captured_at: Generated<Timestamp>;
  count: Generated<number>;
  id: Generated<Int8>;
  sentiment: string | null;
  term: string;
}

export interface LeaderArticles {
  crisis_score: Numeric | null;
  id: Generated<Int8>;
  leader_id: number;
  published_at: Timestamp | null;
  sentiment: string | null;
  source: string | null;
  title: string | null;
}

export interface Leaders {
  id: Generated<number>;
  name: string;
  organization: string | null;
  photo_uri: string | null;
  position: string | null;
}

export interface LeaderSentiment {
  article_count: number | null;
  captured_at: Generated<Timestamp>;
  id: Generated<Int8>;
  insight: string | null;
  leader_id: number;
  prediction_jsonb: Json | null;
  score: Numeric | null;
  trend: string | null;
}

export interface MarketTicker {
  captured_at: Generated<Timestamp>;
  delta: Numeric | null;
  id: Generated<Int8>;
  label: string;
  value: string | null;
}

export interface Predictions {
  answer_label: string | null;
  captured_at: Generated<Timestamp>;
  id: Generated<number>;
  probability: number | null;
  question: string;
  reasoning: string | null;
  timeframe: string | null;
  tone: string | null;
}

export interface Sessions {
  expires_at: Timestamp;
  id: string;
  user_id: number;
}

export interface SocialActors {
  avatar: string | null;
  avg_engagement: number | null;
  brand_mentions: number | null;
  brand_summary: string | null;
  collab_opportunity: string | null;
  credibility: Numeric | null;
  followers: Int8 | null;
  handle: string;
  id: Generated<number>;
  influence: Numeric | null;
  influence_analysis: string | null;
  name: string | null;
  platform: string | null;
  posts_7d: number | null;
  recommended_actions: string | null;
  risk_level: string | null;
  sentiment: Numeric | null;
  status: string | null;
  themes: Json | null;
  total_engagement: Int8 | null;
  updated_at: Generated<Timestamp | null>;
}

export interface Sources {
  cadence_sec: Generated<number>;
  config_jsonb: Json | null;
  enabled: Generated<boolean>;
  endpoint: string | null;
  id: Generated<number>;
  last_run_at: Timestamp | null;
  name: string;
  platform: string | null;
  type: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  last_login_at: Timestamp | null;
  password_hash: string | null;
  role: string;
  status: string;
}

export interface DB {
  actor_posts: ActorPosts;
  ai_conversations: AiConversations;
  ai_messages: AiMessages;
  alembic_version: AlembicVersion;
  article_enrichment: ArticleEnrichment;
  articles: Articles;
  audit_log: AuditLog;
  cities: Cities;
  city_metrics: CityMetrics;
  crisis_snapshots: CrisisSnapshots;
  dashboard_layouts: DashboardLayouts;
  insights: Insights;
  keywords: Keywords;
  leader_articles: LeaderArticles;
  leader_sentiment: LeaderSentiment;
  leaders: Leaders;
  market_ticker: MarketTicker;
  predictions: Predictions;
  sessions: Sessions;
  social_actors: SocialActors;
  sources: Sources;
  users: Users;
}
